import type { Reagent } from "@/lib/app-types";

export type StarterReagentSeed = Pick<Reagent, "name" | "iconUrl" | "profession" | "currentPrice">;

export const STARTER_REAGENTS: StarterReagentSeed[] = [
  { name: "Strange Dust", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Soul Dust", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Vision Dust", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Dream Dust", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Illusion Dust", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Arcane Dust", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Lesser Magic Essence", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Greater Magic Essence", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Lesser Astral Essence", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Greater Astral Essence", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Lesser Mystic Essence", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Greater Mystic Essence", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Lesser Nether Essence", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Greater Nether Essence", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Lesser Eternal Essence", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Greater Eternal Essence", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Lesser Planar Essence", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Greater Planar Essence", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Small Glimmering Shard", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Large Glimmering Shard", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Small Glowing Shard", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Large Glowing Shard", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Small Radiant Shard", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Large Radiant Shard", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Small Brilliant Shard", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Large Brilliant Shard", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Small Prismatic Shard", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Large Prismatic Shard", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Nexus Crystal", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Void Crystal", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Linen Cloth", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Wool Cloth", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Silk Cloth", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Mageweave Cloth", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Runecloth", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Netherweave Cloth", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Ruined Leather Scraps", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Light Leather", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Medium Leather", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Heavy Leather", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Thick Leather", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Rugged Leather", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Knothide Leather", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Fel Hide", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Thick Clefthoof Leather", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Wind Scales", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Nether Dragonscales", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Cobra Scales", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Copper Ore", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Tin Ore", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Silver Ore", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Iron Ore", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Mithril Ore", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Thorium Ore", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Fel Iron Ore", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Adamantite Ore", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Eternium Ore", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Khorium Ore", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Rough Stone", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Coarse Stone", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Heavy Stone", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Solid Stone", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Dense Stone", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Peacebloom", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Silverleaf", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Earthroot", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Mageroyal", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Briarthorn", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Bruiseweed", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Wild Steelbloom", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Kingsblood", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Liferoot", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Fadeleaf", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Goldthorn", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Khadgar's Whisker", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Sungrass", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Blindweed", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Ghost Mushroom", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Gromsblood", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Golden Sansam", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Dreamfoil", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Mountain Silversage", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Felweed", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Dreaming Glory", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Ragveil", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Terocone", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Ancient Lichen", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Mana Thistle", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Nightmare Vine", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Netherbloom", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Malachite", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Tigerseye", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Shadowgem", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Moss Agate", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Citrine", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Jade", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Aquamarine", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Star Ruby", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Large Opal", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Azerothian Diamond", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Blue Sapphire", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Huge Emerald", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Blood Garnet", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Flame Spessarite", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Deep Peridot", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Golden Draenite", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Azure Moonstone", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Shadow Draenite", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Living Ruby", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Noble Topaz", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Dawnstone", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Star of Elune", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Nightseye", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Talasite", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Mote of Fire", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Mote of Water", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Mote of Air", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Mote of Earth", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Mote of Life", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Mote of Mana", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Mote of Shadow", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Primal Fire", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Primal Water", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Primal Air", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Primal Earth", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Primal Life", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Primal Mana", iconUrl: "", profession: "Any", currentPrice: 0 },
  { name: "Primal Shadow", iconUrl: "", profession: "Any", currentPrice: 0 },
];
